export const data = [
  {
    id: 1,
    name: "Irwan Adinata",
    email: "irwan.adinata@gmail.com",
    nomor: "081234567890",
    role: "Admin",
    alamat: "Bandung",
    ibu_kandung: "Siti",
  },
  {
    id: 2,
    name: "John Doe",
    email: "john.doe@gmail.com",
    nomor: "082145678921",
    role: "User",
    alamat: "Jakarta",
    ibu_kandung: "Maria",
  },
  {
    id: 3,
    name: "Tamin Rahman",
    email: "tamin.rahman@gmail.com",
    nomor: "083345678932",
    role: "Moderator",
    alamat: "Surabaya",
    ibu_kandung: "Rukmini",
  },
  {
    id: 4,
    name: "Bara Putra",
    email: "bara.putra@gmail.com",
    nomor: "084556789543",
    role: "User",
    alamat: "Yogyakarta",
    ibu_kandung: "Nurhayati",
  },
];
